### ISSUE TITLE
Setup TDD Design as Test Runner Smoke

### ISSUE THREAD

**Issue by dorukugur** [rifaterdemsahin/aif#228]
https://docs.unity3d.com/Manual/testing-editortestsrunner.html

**Comment by dorukugur** [comment]
https://www.youtube.com/watch?v=MWS4aSO7HAo

**Comment by dorukugur** [comment]
If the button is unable to click, the testrunnes should catch that.

**Comment by rifaterdemsahin** [comment]
Please share this feature with @Neutrinora 
![image](https://user-images.githubusercontent.com/5270036/44606607-97260200-a7e5-11e8-8ea0-110b992b5921.png)

**Comment by dorukugur** [comment]
I tried to create TDD architecture to test Intro scene by C# script, unity TestRunner. The test goal: check button active self, if it is not enable, testing steps show error with its description. However, it is enable during testing, steps of testing say that the goal is working properly. @rifaterdemsahin @Neutrinora 

<img width="1280" alt="ekran resmi 2018-08-25 23 59 52" src="https://user-images.githubusercontent.com/17084517/44622578-c317b500-a8c3-11e8-9ea5-8d623758a537.png">
<img width="1280" alt="ekran resmi 2018-08-26 00 00 03" src="https://user-images.githubusercontent.com/17084517/44622579-c448e200-a8c3-11e8-968a-005d5140381f.png">
<img width="1280" alt="ekran resmi 2018-08-26 00 00 29" src="https://user-images.githubusercontent.com/17084517/44622580-c57a0f00-a8c3-11e8-8a08-5c371ba5320a.png">
<img width="1280" alt="ekran resmi 2018-08-26 00 05 47" src="https://user-images.githubusercontent.com/17084517/44622581-cb6ff000-a8c3-11e8-8f7c-5db983b2b426.png">

**Comment by dorukugur** [comment]
We're going to focus on smoke sanity testing.

**Comment by dorukugur** [comment]
Find clicking run all function automatically.

**Comment by dorukugur** [comment]
Find away how to stop in a specific scene.

**Comment by dorukugur** [comment]
Create a test for each scene which specific test names.

**Comment by dorukugur** [comment]
Enum for scenes.

**Comment by dorukugur** [comment]
Learn how to set the test indexes on testrunner steps.

**Comment by dorukugur** [comment]
https://www.reddit.com/r/Unity3D/comments/9afoda/how_to_integrate_unity_testrunner_with_unity_cloud/

**Comment by dorukugur** [comment]
![image](https://user-images.githubusercontent.com/17084517/44628890-3287b600-a951-11e8-855d-0afdca6f224a.png)

**Comment by dorukugur** [comment]
https://developer.cloud.unity3d.com/orgs/rifaterdemsahin/projects/hare/

**Comment by makif6111** [comment]
will every scene have a unity test method?

**Comment by dorukugur** [comment]
Almost yes. But some scenes and their test methods are empty right now.

**Comment by rifaterdemsahin** [comment]
@makif6111 practical testing from here also works

Rigiht now test all fails
![image](https://user-images.githubusercontent.com/5270036/44644105-cd70a680-a9ca-11e8-9c7d-467d3ba0588a.png)

**Comment by rifaterdemsahin** [comment]
@dorukugur it works when triggered alone
![image](https://user-images.githubusercontent.com/5270036/44644324-99e24c00-a9cb-11e8-85c9-1f0a97b46e6a.png)


please check the changes from @Neutrinora

**Comment by rifaterdemsahin** [comment]
Basic page load is even ok.
![image](https://user-images.githubusercontent.com/5270036/44644786-3d802c00-a9cd-11e8-9d93-9d8db058157a.png)


@Neutrinora as this is a smoke test just loading can be enough.

If moving the keys cause more than 30 lines of code than it might create more issue than the gain.
![image](https://user-images.githubusercontent.com/5270036/44644833-656f8f80-a9cd-11e8-99f6-57e1da9ce54a.png)

**Comment by rifaterdemsahin** [comment]
@dorukugur please check the comments for them to make sense in tests
![image](https://user-images.githubusercontent.com/5270036/44644884-8932d580-a9cd-11e8-82f7-ef08c4b897fa.png)

**Comment by rifaterdemsahin** [comment]
this smoke test runners will be used like this
https://drive.google.com/file/d/1ct1_VfF6zzCWInCpGEDInLcCI3-ox_af/view?usp=sharing
