### ISSUE TITLE
Holding states in the game

### ISSUE THREAD

**Issue by rifaterdemsahin** [rifaterdemsahin/aif#251]
Score and Story positioon  and read stories

**Comment by Treslina** [comment]
I should close this issue after getting permission. Enumerations of these states are :

```
public enum Scenes
{
    Loading = 0,
    Intro = 1,
    Menu = 2,
    Story = 3,
    Game = 4,
    Score = 5,
    Victory = 6
}
```

**Comment by Treslina** [comment]
@rifaterdemsahin I get the permission to close other contributors' issues so I am closing it.
