### ISSUE TITLE
Second Business Visa Application

### ISSUE THREAD

**Issue by CaglaCetinkaya** [rifaterdemsahin/aif#289]
Check all the accounts and documents related to visa applicatin

**Comment by rifaterdemsahin** [comment]
![image](https://user-images.githubusercontent.com/5270036/45323843-4bdd5480-b544-11e8-867e-45020de6c347.png)

**Comment by rifaterdemsahin** [comment]
@CaglaCetinkaya please create a todo list here so we can focus on this task.

**Comment by rifaterdemsahin** [comment]
vat every 3 months : 
todo : we get the confirmation of online VAT. How much money we paid money hmrc

**Comment by rifaterdemsahin** [comment]
![image](https://user-images.githubusercontent.com/5270036/45387465-0edd9480-b60e-11e8-8ee1-6b86d74509a7.png)


confirm

**Comment by CaglaCetinkaya** [comment]
Certificate of incorporation Memorandum of Association 

Company Information 

Share certificate 

Companies House letter  

Accountants letter  

XXX Ltd Reports and Accounts  

XXX Ledgers report from .... until .....

Company Tax Return CT600 for year ending .....

Self-Assessment Tax Return for year ending .....

Payslips from ..... – .....

P60 for year ending April 2017 

Dividend breakdown and Dividend vouchers 

Accounting period overview 

Tax year overview 

Application to HMRC registering as PAYE as an employer 

HMRC Letter with PAYE reference dated ....

HMRC registering for Corporation Tax 

HMRC letter regarding Corporation Tax  

HMRC VAT registration letter dated ....

Certificate of Registration for VAT  

VAT Certificate 

VAT Returns from ....– ....(including customer invoices and business expenses)
