### ISSUE TITLE
Respond to upwork and find a freelancers to complete the task

### ISSUE THREAD

**Issue by rifaterdemsahin** [rifaterdemsahin/aif#290]
https://www.upwork.com/ab/applicants/1034327570036359168/applicants?sort=bestmatch

**Comment by rifaterdemsahin** [comment]
TODO : Cagla open upwork account
TODO : Share your email with erdem
TODO : enter the team 
TODO : Reply to this task
TODO: Find a freelancer
TDODO : do the task
TODO : send images to erdem

**Comment by rifaterdemsahin** [comment]
Upwork team
-- | -- | --
pexabo | pexabo (20353590) | ActionToggle Actions Dropdown

**Comment by rifaterdemsahin** [comment]
![image](https://user-images.githubusercontent.com/5270036/45324366-d7a3b080-b545-11e8-9a1e-23bbc53e5b93.png)

**Comment by rifaterdemsahin** [comment]
![image](https://user-images.githubusercontent.com/5270036/45324606-87791e00-b546-11e8-8298-e70814e66347.png)

**Comment by rifaterdemsahin** [comment]
make sure that we get indexed with DevOps related keywords
and don't be shy about apologizing to people it is ok to make mistakes
we can use multiple people to complete task.

![image](https://user-images.githubusercontent.com/5270036/45385732-80ffaa80-b609-11e8-8590-8054d4f08df0.png)

**Comment by CaglaCetinkaya** [comment]
Use Google Drive format to take Images and Images have to be high quality and curiosity

**Comment by CaglaCetinkaya** [comment]
Hannah has been hired,
I created a google document messaged her to get her email address. Have not heard from her yet
