### ISSUE TITLE
Airline ticket

### ISSUE THREAD

**Issue by rifaterdemsahin** [rifaterdemsahin/aif#291]
Go on friday and comeback on monday 

Sample search.
https://www.skyscanner.net/transport/flights/uk/ista/181005/?adultsv2=1&childrenv2=&cabinclass=economy&rtn=0&preferdirects=false&outboundaltsenabled=false&inboundaltsenabled=false

**Comment by rifaterdemsahin** [comment]
Luton(airport) or Stansted works for me.

**Comment by rifaterdemsahin** [comment]
fly on friday and come sunday or monday morning not to miss a day

**Comment by rifaterdemsahin** [comment]
focus on bank holidays
focus on the flights with 130 pounds one way
sabiha gokcen and ataturk is ok for me to fly

**Comment by rifaterdemsahin** [comment]
September it is minunim 250 !
We could do october!

**Comment by rifaterdemsahin** [comment]
![image](https://user-images.githubusercontent.com/5270036/45386108-6e39a580-b60a-11e8-8ffc-8b287c899e33.png)

**Comment by rifaterdemsahin** [comment]
i can go to corby : think on the plane ticket

**Comment by rifaterdemsahin** [comment]
please create a document for me to understand.
Have the time lines easy to consume.

**Comment by rifaterdemsahin** [comment]
simple facts are fine
![image](https://user-images.githubusercontent.com/5270036/45386314-fb7cfa00-b60a-11e8-9a68-7513696ed255.png)

**Comment by rifaterdemsahin** [comment]
Stansted and Luton are at the same north line
![image](https://user-images.githubusercontent.com/5270036/45386424-40a12c00-b60b-11e8-9846-18beeeef3d2c.png)

**Comment by rifaterdemsahin** [comment]
this is the wrong time cagla...
Friday there is a contract.
Saturday 0:05 is ok not on friday
![image](https://user-images.githubusercontent.com/5270036/45386586-9970c480-b60b-11e8-94ba-f0484c199fc3.png)

**Comment by rifaterdemsahin** [comment]
bus does not work...i will get a cab to oakham from corby.

**Comment by CaglaCetinkaya** [comment]
https://docs.google.com/document/d/1t3i_39-u58JCuD_SnG6zrrJgyapCMWOmX4LG8hPEMTE/edit

Document created, Please have a look

**Comment by rifaterdemsahin** [comment]
@CaglaCetinkaya please create one for 5 of october.
one document

**Comment by rifaterdemsahin** [comment]
![15368718459126510254814236725501](https://user-images.githubusercontent.com/5270036/45515107-1e401780-b79f-11e8-82d4-cde3ba0ff803.jpg)
Ok

**Comment by CaglaCetinkaya** [comment]
Waiting for Erdem to decide to dates
