### ISSUE TITLE
Project Collabrators in Kickstarter

### ISSUE THREAD

**Issue by rifaterdemsahin** [rifaterdemsahin/aif#292]
cagla
![image](https://user-images.githubusercontent.com/5270036/45325199-2d795800-b548-11e8-82bc-d8865c2f2b30.png)

**Comment by rifaterdemsahin** [comment]
@CaglaCetinkaya i am waiting for your confirmation of kickstarter email.
please put it here.

**Comment by CaglaCetinkaya** [comment]
I signed in for Kickstarter could not see any confirmation email.

**Comment by CaglaCetinkaya** [comment]
Hardrockconsultancy@hotmail.com
Waiting for Erol's email.
