### ISSUE TITLE
E2 Application

### ISSUE THREAD

**Issue by CaglaCetinkaya** [rifaterdemsahin/aif#307]
USA startup visa

**Comment by rifaterdemsahin** [comment]
https://entrepreneurhandbook.co.uk/entrepreneur-visa-options-for-the-united-states/

**Comment by CaglaCetinkaya** [comment]
E-2 Treaty Investor visa
The E-2 Treaty Investor Visa is an excellent option for businesses that are owned and operated by ****UK nationals.****  The visa is based on a treaty between the UK and the US designed to encourage investment in each country.  It requires the applicant to show that a substantial investment has been made in the US in establishing the US business.  The US business should be able to support the investor as well as at least a couple of local workers.  Visas can be issued for up to 5 years at a time
