### ISSUE TITLE
quickbooks invoice generate

### ISSUE THREAD

**Issue by rifaterdemsahin** [rifaterdemsahin/aif#310]
start with yours

**Comment by rifaterdemsahin** [comment]
this will automate our processes.

will be seamless with bank integration and upload will not be needed.

**Comment by rifaterdemsahin** [comment]
![image](https://user-images.githubusercontent.com/5270036/45513360-5c870800-b79a-11e8-8003-843dc7e2f0db.png)


send it friday night

**Comment by CaglaCetinkaya** [comment]
Created the invoice will send it in email to MMT Digita;

**Comment by CaglaCetinkaya** [comment]
Has been done
