### ISSUE TITLE
dependant application

### ISSUE THREAD

**Issue by rifaterdemsahin** [rifaterdemsahin/aif#314]
coordinate with ece

**Comment by CaglaCetinkaya** [comment]
https://www.gov.uk/turkish-business-person/family-members

Documents you must provide
For each family member you must have:

a current passport or other valid travel identification
2 passport size colour photographs
proof of your relationship, for example a marriage certificate, evidence that you live together, birth certificate
proof they will live permanently with you
proof that you have sole responsibility for any dependants aged under 21 if the other parent will not be in the UK, for example written permission or relevant legal documents
proof that you can support and house yourself and your dependants during your stay, for example bank statements or payslips for the last 6 months
their tuberculosis test results if they’re from a country where you have to take the test

https://www.visa4uk.fco.gov.uk/home/welcome
