### ISSUE TITLE
Find one or two bedroom flat, house

### ISSUE THREAD

**Issue by CaglaCetinkaya** [rifaterdemsahin/aif#315]
NG11 6QA close to work

**Comment by rifaterdemsahin** [comment]
@CaglaCetinkaya please include the research here

**Comment by CaglaCetinkaya** [comment]
https://www.rightmove.co.uk/property-to-rent/property-66737692.html
Above link is the nearest one to your workplace 3 bed furnished £2500 pcm
https://www.rightmove.co.uk/property-to-rent/property-67562320.html
This one is ideal 3 bed furnished £775 pcm
https://www.rightmove.co.uk/property-to-rent/property-56446050.html
2 bed furnished £910 pcm
https://www.rightmove.co.uk/property-to-rent/property-62039875.html
3 bed furnished £2380
https://www.rightmove.co.uk/property-to-rent/property-69309194.html
Room £400

**Comment by CaglaCetinkaya** [comment]
****
https://uk.hotels.com/ho203047/?q-check-out=2018-10-07&FPQ=2&q-check-in=2018-09-29&WOE=7&WOD=6&q-room-0-children=0&pa=1&tab=description&JHR=6&q-room-0-adults=2&YGF=7&MGT=7&ZSX=0&SYE=3
8 nights £779

https://uk.hotels.com/ho205371/?q-check-out=2018-10-07&FPQ=3&q-check-in=2018-09-29&WOE=7&WOD=6&q-room-0-children=0&pa=2&tab=description&JHR=7&q-room-0-adults=2&YGF=7&MGT=7&ZSX=0&SYE=3
8 nights £789

https://uk.hotels.com/ho668080416/?pa=1&tab=description&q-room-0-adults=1&YGF=7&MGT=7&WOE=7&WOD=6&ZSX=0&SYE=3&q-room-0-children=0

This hotel is in ruddinghton there is no availability but you might try all comments are very good.

https://uk.hotels.com/ho735334496/?pa=1&tab=description&q-room-0-adults=1&YGF=7&MGT=7&WOE=7&WOD=6&ZSX=0&SYE=3&q-room-0-children=0

This hotel is in ruddinghton there is no availability but you might try all comments are very good.

**Comment by CaglaCetinkaya** [comment]
https://www.booking.com/hotel/gb/ibis-nottingham-centre.en-gb.html?label=gen173nr-1FCAEoggJCAlhYSDNYBGhQiAEBmAEuwgEKd2luZG93cyAxMMgBDNgBAegBAfgBC5ICAXmoAgM;sid=847650887041349a555e12098becfe7b;aer=1;all_sr_blocks=4472302_102726774_0_2_0;checkin=2018-09-29;checkout=2018-10-07;dest_id=-2611176;dest_type=city;dist=0;group_adults=1;group_children=0;hapos=7;highlighted_blocks=4472302_102726774_0_2_0;hpos=7;no_rooms=1;room1=A;sb_price_type=total;spdest=ci%2F-2611176;spdist=3.0;srepoch=1537282432;srfid=f71a6da749267fb74759162d5f260c99dacd7da8X7;srpvid=883d68bf694e0113;type=total;ucfs=1&#hotelTmpl

Ibis £640 for 8 nights

**Comment by rifaterdemsahin** [comment]
![image](https://user-images.githubusercontent.com/5270036/45714464-933d9380-bb89-11e8-9b7a-53e689dcf665.png)


will go on friday and saturday......explore and come back

**Comment by rifaterdemsahin** [comment]
@CaglaCetinkaya 
https://docs.google.com/document/d/1i_ch7_tdNk0ill4wUUZ6zL4BP1cuh7N6yLh9E-09o8c/edit

please plan for this friday and i would explore the area.
please set all meeting.airbnb and spareroom contacts please arrange arrange them

**Comment by CaglaCetinkaya** [comment]
SKY CAB £135

**Comment by CaglaCetinkaya** [comment]
Room Links
https://www.rightmove.co.uk/property-to-rent/property-56512422.html

https://www.spareroom.co.uk/flatshare/flatshare_detail.pl?
flatshare_id=10183306&search_results=%2Fflatshare%2Fnottingham%3Flocation_type%3Darea%26flatshare_type%3Doffered%26showme_1beds%3DY%26showme_buddyup_properties%3DY%26showme_rooms%3DY%26per%3Dpcm%26min_rent%3D501%26show_results%3Das%20a%20map%26resume_last_search%3D1

https://www.spareroom.co.uk/flatshare/flatshare_detail.pl?flatshare_id=10192270&search_results=%2Fflatshare%2Fnottingham%3Flocation_type%3Darea%26flatshare_type%3Doffered%26showme_1beds%3DY%26showme_buddyup_properties%3DY%26showme_rooms%3DY%26per%3Dpcm%26min_rent%3D501%26ensuite%3DY%26show_results%3Das%20a%20map%26resume_last_search%3D1
note: He will text me Friday night.

+44 7951 776616
Message Send to Sam from Multi net

https://www.spareroom.co.uk/flatshare/flatshare_detail.pl?flatshare_id=2936352&search_id=719204758&city_id=&flatshare_type=offered&search_results=%2Fflatshare%2F%3Fsearch_id%3D719204758%26&

https://www.spareroom.co.uk/flatshare/flatshare_detail.pl?flatshare_id=2936352&search_id=719209510&city_id=&flatshare_type=offered&search_results=%2Fflatshare%2F%3Fsearch_id%3D719209510%26&

Slatter and Brandley ages policy they do not accept if you are over 34 and for rent house they have long-term policiy. but its good agent atleats you might wanna try

**Comment by CaglaCetinkaya** [comment]
https://www.spareroom.co.uk/flatshare/flatshare_detail.pl?flatshare_id=5190016&search_id=719209510&city_id=&flatshare_type=offered&search_results=%2Fflatshare%2F%3Foffset%3D20%26search_id%3D719209510%26sort_by%3Dage%26mode%3Dlist&

Muli Let
