### ISSUE TITLE
automation of image posting in linkedin

### ISSUE THREAD

**Issue by rifaterdemsahin** [rifaterdemsahin/aif#320]
Jigars code to was
Run it in intervals
İnclude links
Make sure it runs every 12 hours
Please estimate the task
https://docs.google.com/document/d/1TYin1xjJNOMgScGmS66DG1Uj-t-vPbv2tk6UPsBtRaw/edit?usp=drivesdk

Should be able to do this

**Comment by rifaterdemsahin** [comment]
Jigar please estimate hours
And give details of the work

**Comment by jigarbshah11** [comment]
I saw your document , I have to save images with title or you will give that?

**Comment by rifaterdemsahin** [comment]
total 7 hrs is too much 
I have created the VM
we can use camtasia for our approach and speedup.

you can record what you do on your screen
and I can watch it

we need to speed up.

how about 4 hours and closing the deal with only screen capture of your work and questions in GitHub.

**Comment by jigarbshah11** [comment]
Okay, I have booked a meeting at Wednesday

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by rifaterdemsahin** [comment]
Great

**Comment by rifaterdemsahin** [comment]
Use calendly

**Comment by jigarbshah11** [comment]
I agree on hours please give me VM access and Please create my milestone.

**Comment by cagla** [comment]
Anlamıyorum, konu nedir?

19 Eyl 2018 Çar 20:03 tarihinde jigarbshah11 <notifications@github.com>
şunu yazdı:
