### ISSUE TITLE
unity hub integration

### ISSUE THREAD

**Issue by rifaterdemsahin** [rifaterdemsahin/aif#345]
![image](https://user-images.githubusercontent.com/5270036/45931567-c86e2b00-bf67-11e8-986d-dea73f827814.png)

**Comment by rifaterdemsahin** [comment]
warnings are great
![image](https://user-images.githubusercontent.com/5270036/45931610-2995fe80-bf68-11e8-9d53-ede934e59265.png)

**Comment by Treslina** [comment]
I got this one too

**Comment by Treslina** [comment]
I informed everyone to install hub to their computers, if anything goes wrong they can reach me to solve these issues, status will be updated when everyone installs.
