### ISSUE TITLE
Test runner default issues

### ISSUE THREAD

**Issue by rifaterdemsahin** [rifaterdemsahin/aif#346]
when opening at anils#
![image](https://user-images.githubusercontent.com/5270036/45931679-336c3180-bf69-11e8-8bf3-929ac7f9f0ac.png)

**Comment by Treslina** [comment]
I got this issue for solving

**Comment by Treslina** [comment]
@dorukugur did you use any special libraries because I'm unable to compile and run the project

**Comment by rifaterdemsahin** [comment]
important issue.
tests are running in ucb 
![image](https://user-images.githubusercontent.com/5270036/45932081-13d80780-bf6f-11e8-8de5-245ad5fc6e8b.png)

**Comment by Treslina** [comment]
The errors are gone when I relaunch the project and everything compiles and runs.

**Comment by Treslina** [comment]
This issue can be closed right now.
