### ISSUE TITLE
UCB build fail

### ISSUE THREAD

**Issue by Treslina** [rifaterdemsahin/aif#379]
Imported feedback form fails the build because "UnityEditor.PlayerSettings" module can't be used in builds because "UnityEditor" namespace can only be used and intended to use in unity editor not in builds. If any developer wants to use UnityEditor namespace, they need to put their script in a seperate "Editor" folder. That is why it is not building. 

I am temporarily fixing the problem to let everyone to work and publish again but we should discuss what to do @rifaterdemsahin @binofly

![image](https://user-images.githubusercontent.com/7457284/46297717-07266580-c5a6-11e8-9934-8bd6f9124e8d.png)

**Comment by binofly** [comment]
Hei @Treslina 
   Use   

> Application.Version 

it should fix this unity build error  and also works on android APK

**Comment by Treslina** [comment]
Thanks @binofly will fix.
